### ISSUE TITLE
Use favicon (worked earlier, not anymore)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#17]

**Comment by juho-jaakkola** [comment]
Do we have the `favicon.ico` file somewhere?

**Comment by michelesbw** [comment]
Yes, in this folder socialbusinessworld.org/httpdocs/mod/time_theme_pro/graphics/favicon

**Comment by feroda** [comment]
At start I put favicon.ico in the root of beta site. I didn't get the result. I thought about changing the webserver setting for the static path /favicon.ico (that I usually override), but I don't think it is the best way, because I have found this

https://elgg.org/discussion/view/790008/how-to-add-a-favicon-in-elgg (obsolete I think)

and searching in the learn.elgg.org documentation I have found only:

http://learn.elgg.org/en/stable/guides/hooks-list.html?highlight=favicon

I have tried to put the favicon in mod/theme_sbw/views/graphics/favicon.ico and flushed the cache but I had not success.

Please @juho-jaakkola bring me the light of your knowledge ;)
BONUS: where should I look to learn? How can I learn similat things by myself next time? which are my faults? ;)

Thank you
