### ISSUE TITLE
Send a message button missing in profile page (see screenshot)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#54]
![screenshot-socialbusinessworld org 2016-10-20 13-54-44](https://cloud.githubusercontent.com/assets/5203511/19558853/f62f661e-96cc-11e6-82ba-c8cf1fc80449.png)

**Comment by juho-jaakkola** [comment]
The button is missing because hypeInbox replaces the [link registration](https://github.com/Elgg/Elgg/blob/2.3/mod/messages/start.php#L430-L433) from the messages plugin with its [own version](https://github.com/hypeJunction/hypeInbox/blob/5.x/classes/hypeJunction/Inbox/HookHandlers.php#L223-L227) but it doesn't define the `'section' => 'action'` that the original one has.

@hypeJunction Do you think the section definition could be added to hypeInbox, or should it be added to SBW separately?

**Comment by hypeJunction** [comment]
Sure, can add to inbox

**Comment by hypeJunction** [comment]
Made a new release of hypeInbox

**Comment by michelesbw** [comment]
Didn't say thank you for this :)
