### ISSUE TITLE
Main menu: add link to marketplace

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#55]

**Comment by michelesbw** [comment]
Marketplace link https://shop.socialbusinessworld.org is correctly set on /admin/appearance/menu_items since previous versions but not in the menu.

**Comment by feroda** [comment]
@juho-jaakkola I have verified the menu item added by @michelesbw in the admin of `beta.socialbusinessworld.org`, the theme seems not to take care of it?

Where could we put it to honour the custom items? 
Or where could we add the entry by hand in the custom theme code?

**Comment by juho-jaakkola** [comment]
Menu items are part of the site structure - something that is identical regardless of the environment (local, beta, production), so they belong to the code instead of site configuration.

Good place to register the menu item would be here: https://github.com/sbwtech/theme_sbw/blob/master/start.php#L54-L84

Site menu items can be ordered by passing in `['sort_by' => 'title']` as second parameter to https://github.com/sbwtech/theme_sbw/blob/master/views/default/page/elements/navbar.php#L4 as described here: http://learn.elgg.org/de/stable/guides/menus.html#creating-a-new-menu

**Comment by juho-jaakkola** [comment]
Hm... actually it may be that they do not in fact get sorted alphabetically, because we have the icon appended to the title.

**Comment by juho-jaakkola** [comment]
What icon should the menu item use?

What are the different translations for the menu item text, or is it "Marketplace" on all languages?

**Comment by michelesbw** [comment]
Marketplace is ok for all languages and the icon was mentioned here https://github.com/sbwtech/theme_sbw/issues/23
It's this one http://fontawesome.io/icon/leaf
